#!/usr/bin/env python3
"""Every task a definition references has a worker — the check behind check-contracts.sh.

Reads the ACTION steps of every workflow definition, the task contracts (.ectask) and what each worker
service registers (contracts/workers/<service>.tasks, generated by that service's ServedTasksTest), and
fails on a gap:

  - a step whose task has no contract, or no topic (the step's own or its contract's);
  - a step whose task no worker serves on that topic — the engine would dispatch it and nobody would
    answer, the step retrying until its deadline;
  - (--cluster) a task topic no live consumer group reads.

Where the definitions come from:

  --ref REF       ec-definitions cloned at REF (default: master, the branch ec1 imports)
  --definitions D a checkout of ec-definitions
  --cluster       what the engine in ec1 has imported (its database), and the task topics' consumer
                  groups in its Redpanda — so a definition pushed but not imported, or a worker that is
                  down, shows too

Also listed, without failing: contracts no step references, and tasks a worker serves that no step
references. Exit status 1 on any gap.
"""
import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

sys.dont_write_bytecode = True
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent
WORKERS = ROOT / "contracts" / "workers"
REPO = "https://github.com/miguelperezcolom/ec-definitions.git"
NS = "ec-demo1"


# ------------------------------------------------------------------------------------------ the sources

def scalar(value):
    value = value.split(" #")[0].strip()
    if len(value) >= 2 and value[0] == value[-1] and value[0] in "'\"":
        value = value[1:-1]
    return value


def parse_contract(text):
    """id, version and topic of a .ectask (YAML, top-level keys only)."""
    fields = {}
    for line in text.splitlines():
        m = re.match(r"^(id|version|topic):\s*(.+)$", line)
        if m:
            fields[m.group(1)] = scalar(m.group(2))
    return fields.get("id"), int(fields.get("version", "1")), fields.get("topic")


def parse_steps(text):
    """The steps of a .ec definition (YAML): each step's id, type, task and topic."""
    steps, step, indent = [], None, None
    in_steps = False
    for line in text.splitlines():
        if re.match(r"^steps:\s*$", line):
            in_steps = True
            continue
        if in_steps and re.match(r"^\S", line) and not line.startswith("#"):
            in_steps = False
        if not in_steps:
            continue
        m = re.match(r"^(\s*)- id:\s*(.+)$", line)
        if m:
            step = {"id": scalar(m.group(2))}
            indent = len(m.group(1)) + 2
            steps.append(step)
            continue
        m = re.match(r"^(\s*)(type|task|topic):\s*(.+)$", line)
        if step is not None and m and len(m.group(1)) == indent:
            step[m.group(2)] = scalar(m.group(3))
    return steps


def from_checkout(root):
    root = Path(root) / "definitions"
    contracts = {}
    for f in sorted((root / "tasks").glob("*.ectask")):
        cid, version, topic = parse_contract(f.read_text())
        contracts[f"{cid}@{version}"] = topic
    definitions = {}
    for f in sorted((root / "workflows").glob("*.ec")):
        text = f.read_text()
        m = re.search(r"^id:\s*(.+)$", text, re.M)
        definitions[scalar(m.group(1)) if m else f.stem] = parse_steps(text)
    return contracts, definitions


def from_git(ref):
    tmp = tempfile.mkdtemp(prefix="ec-definitions-")
    r = subprocess.run(["git", "clone", "-q", "--depth", "1", "--branch", ref, REPO, tmp],
                       capture_output=True, text=True)
    if r.returncode != 0:
        # a commit, not a branch or tag
        subprocess.run(["git", "clone", "-q", REPO, tmp], check=True, capture_output=True)
        subprocess.run(["git", "-C", tmp, "checkout", "-q", ref], check=True, capture_output=True)
    head = subprocess.run(["git", "-C", tmp, "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip()
    contracts, definitions = from_checkout(tmp)
    return contracts, definitions, f"ec-definitions@{ref} ({head})"


def from_cluster():
    sys.path.insert(0, str(HERE))
    import ec1
    contracts = {ref: topic for ref, topic in ec1.psql("workflow", "select ref, topic from ec_task_contract")}
    definitions = {}
    for did, steps in ec1.psql("workflow",
                               "select id, replace(steps_json, chr(10), ' ') from workflow_definition_entity "
                               "where coalesce(runtime_status, '') <> 'ARCHIVED'"):
        definitions[did] = [{k: s.get(k) for k in ("id", "type", "task", "topic")} for s in json.loads(steps)]
    return contracts, definitions, "the engine in ec1 (its imported definitions, archived ones aside)"


def served():
    """(ref, topic) → the services that serve it, from contracts/workers/*.tasks."""
    result = {}
    for f in sorted(WORKERS.glob("*.tasks")):
        for line in f.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                ref, topic = line.split()
                result.setdefault((ref, topic), []).append(f.stem)
    return result


def live_topics():
    """Task topics with a consumer group that has members, in ec1's Redpanda."""
    pod = subprocess.run(["kubectl", "-n", NS, "get", "pod", "-o", "name"], capture_output=True, text=True).stdout.split()
    pod = next(p for p in pod if "redpanda" in p and "console" not in p)
    groups = subprocess.run(["kubectl", "-n", NS, "exec", pod, "--", "rpk", "group", "list"],
                            capture_output=True, text=True).stdout.split("\n")[1:]
    topics = {}
    for g in groups:
        name = g.split()[1] if len(g.split()) > 1 else None
        if not name:
            continue
        out = subprocess.run(["kubectl", "-n", NS, "exec", pod, "--", "rpk", "group", "describe", name],
                             capture_output=True, text=True).stdout
        members = re.search(r"^MEMBERS\s+(\d+)", out, re.M)
        if not members or int(members.group(1)) == 0:
            continue
        for line in out.splitlines():
            parts = line.split()
            if len(parts) > 3 and parts[0] not in ("GROUP", "COORDINATOR", "STATE", "BALANCER", "MEMBERS",
                                                    "TOTAL-LAG", "TOPIC") and parts[1].isdigit():
                topics.setdefault(parts[0], set()).add(name)
    return topics


# ------------------------------------------------------------------------------------------- the check

def resolve(task, contracts):
    """A step's task reference as the engine pins it: <id>@<version>, a bare id → its highest version."""
    if re.search(r"@\d+$", task):
        return task if task in contracts else None
    versions = [int(r.split("@")[1]) for r in contracts if r.split("@")[0] == task]
    return f"{task}@{max(versions)}" if versions else None


def check(contracts, definitions, source, cluster=False):
    workers = served()
    serving = {ref for ref, _ in workers}
    gaps, notes, rows = [], [], []
    referenced = set()
    for did, steps in sorted(definitions.items()):
        for step in steps:
            if step.get("type") != "ACTION":
                continue
            task = step.get("task")
            if not task:
                # No task: the engine sends no taskId and the SDK (2.23.1) serves the step id as a
                # contract id. Fine if some worker does, on the step's topic; a gap otherwise.
                topic = step.get("topic")
                by_step = [s for (r, t), ss in workers.items() if r.split("@")[0] == step["id"] and t == topic for s in ss]
                if by_step:
                    notes.append(f"{did}/{step['id']}: names no task; served by its step id ({', '.join(by_step)})")
                else:
                    gaps.append(f"{did}/{step['id']}: names no task, and no worker serves its step id on {topic}")
                continue
            ref = resolve(task, contracts)
            if ref is None:
                gaps.append(f"{did}/{step['id']}: task {task} has no contract")
                continue
            referenced.add(ref)
            topic = step.get("topic") or contracts.get(ref)
            if not topic:
                gaps.append(f"{did}/{step['id']}: {ref} has no topic (neither the step nor its contract says one)")
                continue
            services = workers.get((ref, topic))
            if not services:
                elsewhere = [f"{t} ({', '.join(s)})" for (r, t), s in workers.items() if r == ref]
                gaps.append(f"{did}/{step['id']}: no worker serves {ref} on {topic}"
                            + (f" — served on {', '.join(elsewhere)}" if elsewhere else ""))
                continue
            rows.append((did, step["id"], ref, topic, ", ".join(services)))
    if cluster:
        live = live_topics()
        for topic in sorted({r[3] for r in rows}):
            if topic not in live:
                gaps.append(f"topic {topic}: no consumer group with members reads it — its worker is down")
    for ref in sorted(set(contracts) - referenced):
        notes.append(f"contract {ref} is referenced by no step")
    for ref in sorted(serving - referenced):
        notes.append(f"{ref} is served ({', '.join(s for (r, _), ss in workers.items() if r == ref for s in ss)}) "
                     "but referenced by no step")
    return rows, gaps, notes


def main(argv):
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    group = parser.add_mutually_exclusive_group()
    group.add_argument("--ref", default="master")
    group.add_argument("--definitions")
    group.add_argument("--cluster", action="store_true")
    parser.add_argument("-q", "--quiet", action="store_true", help="only the gaps and the verdict")
    args = parser.parse_args(argv)
    if args.cluster:
        contracts, definitions, source = from_cluster()
    elif args.definitions:
        contracts, definitions = from_checkout(args.definitions)
        source = args.definitions
    else:
        contracts, definitions, source = from_git(args.ref)
    rows, gaps, notes = check(contracts, definitions, source, cluster=args.cluster)
    print(f"Definitions: {source}; workers: {WORKERS.relative_to(ROOT)}/*.tasks")
    if not args.quiet:
        for did, step, ref, topic, services in rows:
            print(f"  ok    {did}/{step}: {ref} on {topic} — {services}")
        for n in notes:
            print(f"  note  {n}")
    for g in gaps:
        print(f"  GAP   {g}")
    print(f"{len(rows)} task steps served, {len(gaps)} gaps" + ("" if gaps else " — every task has its worker"))
    return 1 if gaps else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
