package io.mateu.ecdemo1.messaging;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;

import java.sql.SQLException;
import java.util.List;

/**
 * The outbox and inbox tables. Their columns are the ones the services' own copies had Hibernate
 * create — {@code outbox_message(seq, binding, message_key, event_type, payload, created_at,
 * published_at, traceparent, tracestate)}, {@code inbox_entry(consumer, event_id, received_at)} — so a
 * service switching to this library keeps its tables and its rows: pending messages are relayed, seen
 * ids still deduplicate.
 *
 * <p>Creating is additive and repeatable: a table that is missing is created, a column this library
 * added (headers, the retry bookkeeping) is added to a table that lacks it, with a default an old
 * writer that does not know it satisfies. Nothing is ever dropped or renamed.
 */
public class MessagingSchema {

    static final Logger log = LoggerFactory.getLogger(MessagingSchema.class);

    final JdbcTemplate jdbc;
    final MessagingProperties properties;
    final boolean postgres;

    public MessagingSchema(JdbcTemplate jdbc, MessagingProperties properties) {
        this.jdbc = jdbc;
        this.properties = properties;
        this.postgres = isPostgres(jdbc);
    }

    static boolean isPostgres(JdbcTemplate jdbc) {
        try {
            var product = jdbc.execute((java.sql.Connection c) -> c.getMetaData().getDatabaseProductName());
            return product != null && product.toLowerCase().contains("postgres");
        } catch (RuntimeException e) {
            log.warn("Cannot tell the database: {}", e.toString());
            return false;
        }
    }

    public boolean postgres() {
        return postgres;
    }

    public void create() {
        var outbox = properties.outbox().table();
        var inbox = properties.inbox().table();
        var index = outbox.replace('.', '_');
        for (var sql : List.of(
                """
                create table if not exists %s (
                    seq bigint generated by default as identity primary key,
                    binding varchar(255) not null,
                    message_key varchar(255),
                    event_type varchar(255) not null,
                    payload varchar not null,
                    created_at timestamp with time zone not null,
                    published_at timestamp with time zone,
                    traceparent varchar(64),
                    tracestate varchar(512)
                )""".formatted(outbox),
                "alter table %s add column if not exists headers varchar".formatted(outbox),
                "alter table %s add column if not exists attempts integer default 0 not null".formatted(outbox),
                "alter table %s add column if not exists next_attempt_at timestamp with time zone".formatted(outbox),
                "alter table %s add column if not exists last_error varchar".formatted(outbox),
                "alter table %s add column if not exists abandoned boolean default false not null".formatted(outbox),
                "create index if not exists %s_pending_idx on %s (published_at, seq)".formatted(index, outbox),
                "create index if not exists %s_key_idx on %s (message_key, seq)".formatted(index, outbox),
                """
                create table if not exists %s (
                    consumer varchar(255) not null,
                    event_id varchar(255) not null,
                    received_at timestamp with time zone,
                    primary key (consumer, event_id)
                )""".formatted(inbox))) {
            jdbc.execute(sql);
        }
        log.debug("Outbox {} and inbox {} ready", outbox, inbox);
    }

    /** Whether a table exists — for a service's startup migration of a table of its own. */
    public static boolean tableExists(JdbcTemplate jdbc, String table) {
        MessagingProperties.checked(table);
        try {
            return Boolean.TRUE.equals(jdbc.execute((java.sql.Connection c) -> {
                var meta = c.getMetaData();
                for (var name : List.of(table, table.toUpperCase(), table.toLowerCase())) {
                    try (var rs = meta.getTables(null, null, name, new String[]{"TABLE"})) {
                        if (rs.next()) {
                            return true;
                        }
                    }
                }
                return false;
            }));
        } catch (RuntimeException e) {
            if (e.getCause() instanceof SQLException) {
                return false;
            }
            throw e;
        }
    }
}
