#!/usr/bin/env bash
# Deploys the whole demo to a Kubernetes cluster, from nothing.
#
#   ./deploy/deploy.sh
#
# Idempotent: every step is an upgrade-or-install, so re-running it after editing anything under
# deploy/ converges the cluster rather than complaining. Passwords are generated once, on the
# first run, and kept in deploy/.secrets/credentials.env (git-ignored) so a second run does not
# invalidate the ones already stored in the cluster.
#
# What it does NOT do, because both are outside the cluster:
#   • build the shell and gateway images — see build-images.sh
#   • create the DNS records — ec1, auth.ec1 and grafana.ec1 must resolve to the ingress
#     controller's LoadBalancer address before Let's Encrypt can issue anything
set -euo pipefail
cd "$(dirname "$0")/.."

NS=ec-demo1
OBS_NS=observability
SECRETS=deploy/.secrets/credentials.env

echo "══ 1/6  Cluster prerequisites: ingress controller and certificate issuer ══"
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx >/dev/null 2>&1 || true
helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1 || true
helm repo add grafana https://grafana.github.io/helm-charts >/dev/null 2>&1 || true
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts >/dev/null 2>&1 || true
helm repo update >/dev/null

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  -n ingress-nginx --create-namespace \
  --set controller.replicaCount=1 \
  --set controller.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set controller.service.type=LoadBalancer \
  --set controller.resources.requests.cpu=100m \
  --set controller.resources.requests.memory=256Mi \
  --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set defaultBackend.enabled=false \
  --wait --timeout 10m

helm upgrade --install cert-manager jetstack/cert-manager \
  -n cert-manager --create-namespace \
  --set crds.enabled=true \
  --set nodeSelector."kubernetes\.io/arch"=amd64 \
  --set webhook.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set cainjector.nodeSelector."kubernetes\.io/arch"=amd64 \
  --wait --timeout 10m

echo
echo "── LoadBalancer address (the DNS records must point here) ──"
kubectl get svc -n ingress-nginx ingress-nginx-controller \
  -o jsonpath='{.status.loadBalancer.ingress[*].ip}{"\n"}'

echo "══ 2/6  Namespaces and secrets ══"
kubectl apply -f deploy/manifests/00-namespace.yaml
kubectl create namespace "$OBS_NS" --dry-run=client -o yaml | kubectl apply -f -

# Generated once and reused: regenerating on every run would rotate the password the running
# PostgreSQL still expects, and the engine would fail to authenticate against its own database.
if [ ! -f "$SECRETS" ]; then
  mkdir -p deploy/.secrets
  {
    echo "# Generated by deploy.sh. Not in version control."
    echo "EC_POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
  } > "$SECRETS"
  chmod 600 "$SECRETS"
  echo "generated $SECRETS"
fi
# shellcheck disable=SC1090
set -a; . "$SECRETS"; set +a

kubectl create secret generic ec-postgres -n "$NS" \
  --from-literal=POSTGRES_DB=workflow \
  --from-literal=POSTGRES_USER=workflow \
  --from-literal=POSTGRES_PASSWORD="$EC_POSTGRES_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic keycloak-admin -n "$NS" \
  --from-literal=password="$KEYCLOAK_ADMIN_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic grafana-admin -n "$OBS_NS" \
  --from-literal=admin-user=admin \
  --from-literal=admin-password="$GRAFANA_ADMIN_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create configmap keycloak-realm -n "$NS" \
  --from-file=ec-demo1-realm.json=deploy/keycloak/ec-demo1-realm.json \
  --dry-run=client -o yaml | kubectl apply -f -

echo "══ 3/6  EventConductor engine (PostgreSQL, Redpanda, orchestrator, forms) ══"
helm upgrade --install ec deploy/chart/eventconductor -n "$NS" \
  -f deploy/values/eventconductor.yaml

echo "══ 4/6  Keycloak, worker, shell, gateway, ingress ══"
kubectl apply -f deploy/manifests/05-clusterissuer.yaml
# The Job is immutable once created, so a re-run has to replace it rather than patch it.
kubectl delete job keycloak-db-init -n "$NS" --ignore-not-found
kubectl apply -f deploy/manifests/10-keycloak.yaml
kubectl apply -f deploy/manifests/20-worker.yaml
kubectl apply -f deploy/manifests/30-shell.yaml
kubectl apply -f deploy/manifests/35-gateway.yaml
kubectl apply -f deploy/manifests/40-ingress.yaml

echo "══ 5/6  Observability (Prometheus, Grafana, Loki, Tempo, Alloy) ══"
helm upgrade --install kps prometheus-community/kube-prometheus-stack \
  -n "$OBS_NS" -f deploy/observability/kube-prometheus-stack.yaml --timeout 15m
helm upgrade --install loki grafana/loki -n "$OBS_NS" -f deploy/observability/loki.yaml --timeout 15m
helm upgrade --install tempo grafana/tempo -n "$OBS_NS" -f deploy/observability/tempo.yaml --timeout 15m
helm upgrade --install alloy grafana/alloy -n "$OBS_NS" -f deploy/observability/alloy.yaml --timeout 15m
kubectl apply -f deploy/observability/servicemonitors.yaml

echo "══ 6/6  Waiting for the workloads ══"
kubectl rollout status deployment/ec-eventconductor-orchestrator -n "$NS" --timeout=10m
kubectl rollout status deployment/ec-eventconductor-forms -n "$NS" --timeout=10m
kubectl rollout status deployment/keycloak -n "$NS" --timeout=10m
kubectl rollout status deployment/worker -n "$NS" --timeout=10m
kubectl rollout status deployment/shell -n "$NS" --timeout=10m
kubectl rollout status deployment/gateway -n "$NS" --timeout=10m

cat <<EOF

Done.

  Console   https://ec1.mateu.io          demo / demo
  Keycloak  https://auth.ec1.mateu.io     admin / \$KEYCLOAK_ADMIN_PASSWORD
  Grafana   https://grafana.ec1.mateu.io  admin / \$GRAFANA_ADMIN_PASSWORD

Passwords are in $SECRETS.
Certificates take a minute: kubectl get certificate -A
EOF
