#!/usr/bin/env bash
# Deploys the whole demo to a Kubernetes cluster, from nothing.
#
#   ./deploy/deploy.sh
#
# Idempotent: every step is an upgrade-or-install, so re-running it after editing anything under
# deploy/ converges the cluster rather than complaining. Passwords are generated once, on the
# first run, and kept in deploy/.secrets/credentials.env (git-ignored) so a second run does not
# invalidate the ones already stored in the cluster.
#
# What it does NOT do, because both are outside the cluster:
#   • build the eight images this repository owns — see build-images.sh
#   • create the DNS records — ec1 and *.ec1 must resolve to the ingress controller's
#     LoadBalancer address before Let's Encrypt can issue anything. The wildcard is what makes
#     console.ec1 work without a new record; it still needs its own certificate, which
#     cert-manager issues on the first request once the name resolves.
set -euo pipefail
cd "$(dirname "$0")/.."

NS=ec-demo1
OBS_NS=observability
SECRETS=deploy/.secrets/credentials.env

echo "══ 1/6  Cluster prerequisites: ingress controller and certificate issuer ══"
helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx >/dev/null 2>&1 || true
helm repo add jetstack https://charts.jetstack.io >/dev/null 2>&1 || true
helm repo add grafana https://grafana.github.io/helm-charts >/dev/null 2>&1 || true
helm repo add prometheus-community https://prometheus-community.github.io/helm-charts >/dev/null 2>&1 || true
helm repo update >/dev/null

helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
  -n ingress-nginx --create-namespace \
  --set controller.replicaCount=1 \
  --set controller.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set controller.service.type=LoadBalancer \
  --set controller.resources.requests.cpu=100m \
  --set controller.resources.requests.memory=256Mi \
  --set controller.admissionWebhooks.patch.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set defaultBackend.enabled=false \
  --wait --timeout 10m

helm upgrade --install cert-manager jetstack/cert-manager \
  -n cert-manager --create-namespace \
  --set crds.enabled=true \
  --set nodeSelector."kubernetes\.io/arch"=amd64 \
  --set webhook.nodeSelector."kubernetes\.io/arch"=amd64 \
  --set cainjector.nodeSelector."kubernetes\.io/arch"=amd64 \
  --wait --timeout 10m

echo
echo "── LoadBalancer address (the DNS records must point here) ──"
kubectl get svc -n ingress-nginx ingress-nginx-controller \
  -o jsonpath='{.status.loadBalancer.ingress[*].ip}{"\n"}'

echo "══ 2/6  Namespaces and secrets ══"
kubectl apply -f deploy/manifests/00-namespace.yaml
kubectl create namespace "$OBS_NS" --dry-run=client -o yaml | kubectl apply -f -

# Generated once and reused: regenerating on every run would rotate the password the running
# PostgreSQL still expects, and the engine would fail to authenticate against its own database.
if [ ! -f "$SECRETS" ]; then
  mkdir -p deploy/.secrets
  {
    echo "# Generated by deploy.sh. Not in version control."
    echo "EC_POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "KEYCLOAK_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "GRAFANA_ADMIN_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    echo "KAFKA_CONSOLE_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=' | head -c 20)"
    echo "GIT_WEBHOOK_SECRET=$(openssl rand -hex 24)"
    echo "CP_POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
    # AES-256 for the control plane's stored LLM credentials. 32 bytes, base64, and it must not
    # be regenerated: nothing re-wraps the stored ciphertext, so a new key makes every catalogued
    # credential undecryptable and they have to be entered again.
    echo "CP_CRYPTO_KEY=$(openssl rand -base64 32)"
    echo "# Not generated: paste an Anthropic API key here to enable the console's chat panel."
    echo "# ANTHROPIC_API_KEY="
  } > "$SECRETS"
  chmod 600 "$SECRETS"
  echo "generated $SECRETS"
fi
# Keys added after a deployment already exists would otherwise never be generated: the block
# above only runs on the very first deploy, and `set -u` then aborts on the first unbound one.
# Appending the missing ones keeps a re-run against an existing cluster working, and leaves every
# password already stored in that cluster exactly as it was.
append_if_missing() {  # name, value
  if ! grep -q "^$1=" "$SECRETS"; then
    echo "$1=$2" >> "$SECRETS"
    echo "added $1 to $SECRETS"
  fi
}
append_if_missing CP_POSTGRES_PASSWORD "$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
# Regenerating this one would make every stored LLM credential undecryptable — nothing re-wraps
# them — so it is written once and then left alone, like the PostgreSQL password above.
append_if_missing CP_CRYPTO_KEY "$(openssl rand -base64 32)"

# shellcheck disable=SC1090
set -a; . "$SECRETS"; set +a

kubectl create secret generic ec-postgres -n "$NS" \
  --from-literal=POSTGRES_DB=workflow \
  --from-literal=POSTGRES_USER=workflow \
  --from-literal=POSTGRES_PASSWORD="$EC_POSTGRES_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic keycloak-admin -n "$NS" \
  --from-literal=password="$KEYCLOAK_ADMIN_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic grafana-admin -n "$OBS_NS" \
  --from-literal=admin-user=admin \
  --from-literal=admin-password="$GRAFANA_ADMIN_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create configmap keycloak-realm -n "$NS" \
  --from-file=ec-demo1-realm.json=deploy/keycloak/ec-demo1-realm.json \
  --dry-run=client -o yaml | kubectl apply -f -
# htpasswd for the Kafka console's ingress. openssl's apr1 is the format nginx expects, and needs
# no apache2-utils on whoever runs this.
kubectl create secret generic kafka-console-auth -n "$NS" \
  --from-literal=auth="admin:$(openssl passwd -apr1 "$KAFKA_CONSOLE_PASSWORD")" \
  --dry-run=client -o yaml | kubectl apply -f -
# Shared by the orchestrator and the forms engine: each reads its own key and ignores the other.
# Both apps verify inbound webhooks against it, and a blank value would make them verify nothing.
kubectl create secret generic ec-git-webhook -n "$NS" \
  --from-literal=WORKFLOW_GITIMPORT_WEBHOOKSECRET="$GIT_WEBHOOK_SECRET" \
  --from-literal=FORMS_GITIMPORT_WEBHOOKSECRET="$GIT_WEBHOOK_SECRET" \
  --dry-run=client -o yaml | kubectl apply -f -
# The control plane's own database and the key its credentials are encrypted with. Both are
# generated, unlike the Anthropic key, because both are derived rather than bought.
kubectl create secret generic ec-cp-postgres -n "$NS" \
  --from-literal=POSTGRES_DB=controlplane \
  --from-literal=POSTGRES_USER=controlplane \
  --from-literal=POSTGRES_PASSWORD="$CP_POSTGRES_PASSWORD" \
  --dry-run=client -o yaml | kubectl apply -f -
kubectl create secret generic ec-cp-crypto -n "$NS" \
  --from-literal=CP_CRYPTO_KEY="$CP_CRYPTO_KEY" \
  --dry-run=client -o yaml | kubectl apply -f -

# The chat agent's Anthropic key. Not generated — it is bought, not derived — so it is only
# created when ANTHROPIC_API_KEY is in the environment or in credentials.env, which is also why
# the deployment marks it optional. Without it the agent still starts and logs why, and the first
# prompt fails with a 401 from Anthropic; every other part of the console is unaffected.
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  kubectl create secret generic ec-anthropic -n "$NS" \
    --from-literal=ANTHROPIC_API_KEY="$ANTHROPIC_API_KEY" \
    --dry-run=client -o yaml | kubectl apply -f -
else
  echo "ANTHROPIC_API_KEY not set — skipping the ec-anthropic secret."
  echo "  The chat panel will answer with a 401 until you add it to $SECRETS and re-run this."
fi

echo "══ 3/6  EventConductor engine (PostgreSQL, Redpanda, orchestrator, forms) ══"
helm upgrade --install ec deploy/chart/eventconductor -n "$NS" \
  -f deploy/values/eventconductor.yaml

echo "══ 4/6  Keycloak, worker, shells, gateway, ingress, demo services, control plane ══"
kubectl apply -f deploy/manifests/05-clusterissuer.yaml
# The Job is immutable once created, so a re-run has to replace it rather than patch it.
kubectl delete job keycloak-db-init -n "$NS" --ignore-not-found
kubectl apply -f deploy/manifests/10-keycloak.yaml
kubectl apply -f deploy/manifests/20-worker.yaml
kubectl apply -f deploy/manifests/30-shell.yaml
kubectl apply -f deploy/manifests/35-gateway.yaml
kubectl apply -f deploy/manifests/40-ingress.yaml
kubectl apply -f deploy/manifests/50-kafka-console.yaml
# The demo services. Their databases first, and by the same replace-not-patch rule as Keycloak's:
# a Job is immutable once created.
kubectl delete job demo-db-init -n "$NS" --ignore-not-found
kubectl apply -f deploy/manifests/55-demo-db-init.yaml
kubectl apply -f deploy/manifests/60-booking.yaml
kubectl apply -f deploy/manifests/61-content.yaml
kubectl apply -f deploy/manifests/62-users.yaml
kubectl apply -f deploy/manifests/63-ia-agent.yaml
# The control console: its database first, then the service, then its shell.
kubectl apply -f deploy/manifests/70-cp-postgres.yaml
kubectl apply -f deploy/manifests/71-ia-control-plane.yaml
kubectl apply -f deploy/manifests/72-control-shell.yaml

echo "══ 5/6  Observability (Prometheus, Grafana, Loki, Tempo, Alloy) ══"
helm upgrade --install kps prometheus-community/kube-prometheus-stack \
  -n "$OBS_NS" -f deploy/observability/kube-prometheus-stack.yaml --timeout 15m
helm upgrade --install loki grafana/loki -n "$OBS_NS" -f deploy/observability/loki.yaml --timeout 15m
helm upgrade --install tempo grafana/tempo -n "$OBS_NS" -f deploy/observability/tempo.yaml --timeout 15m
helm upgrade --install alloy grafana/alloy -n "$OBS_NS" -f deploy/observability/alloy.yaml --timeout 15m
kubectl apply -f deploy/observability/servicemonitors.yaml

# The two dashboards written for this deployment, as ConfigMaps the Grafana sidecar picks up —
# never imported through the UI. Grafana keeps its database on an emptyDir here, so a dashboard
# imported by hand lives exactly as long as the pod does: any upgrade that recreates it takes them
# with it, without a word, and the first anyone knows is a panel that is not there any more. It
# happened once, to both of them.
#
# The key each is filed under has to be unique across every dashboard ConfigMap in the cluster, not
# merely within its own. The sidecar writes all of them into one flat /tmp/dashboards, and Grafana
# derives a dashboard's internal id from that path — so a second `nodes.json` (the chart ships one,
# for Node Exporter) is refused with "deprecatedInternalID is already in use" and simply never
# appears, while the sidecar reports having written it. That is why the second is keyed
# `eventconductor-nodes.json` and not by its own filename.
apply_dashboard() {  # name, key, file
  kubectl create configmap "grafana-dashboard-$1" -n "$OBS_NS" \
    --from-file="$2=deploy/observability/dashboards/$3" --dry-run=client -o yaml \
    | kubectl label --local -f - grafana_dashboard=1 -o yaml \
    | kubectl apply -f -
}
apply_dashboard eventconductor       eventconductor.json       eventconductor.json
apply_dashboard eventconductor-nodes eventconductor-nodes.json nodes.json

echo "══ 6/6  Waiting for the workloads ══"
kubectl rollout status deployment/ec-eventconductor-orchestrator -n "$NS" --timeout=10m
kubectl rollout status deployment/ec-eventconductor-forms -n "$NS" --timeout=10m
kubectl rollout status deployment/keycloak -n "$NS" --timeout=10m
kubectl rollout status deployment/worker -n "$NS" --timeout=10m
kubectl rollout status deployment/shell -n "$NS" --timeout=10m
kubectl rollout status deployment/gateway -n "$NS" --timeout=10m
kubectl rollout status deployment/kafka-console -n "$NS" --timeout=10m
kubectl rollout status deployment/booking -n "$NS" --timeout=10m
kubectl rollout status deployment/content -n "$NS" --timeout=10m
kubectl rollout status deployment/users -n "$NS" --timeout=10m
kubectl rollout status deployment/ia-agent -n "$NS" --timeout=10m
kubectl rollout status deployment/cp-postgres -n "$NS" --timeout=10m
kubectl rollout status deployment/ia-control-plane -n "$NS" --timeout=10m
kubectl rollout status deployment/control-shell -n "$NS" --timeout=10m

cat <<EOF

Done.

  Console   https://ec1.mateu.io          demo / demo
  Control   https://console.ec1.mateu.io  demo / demo  (needs the realm role \`ai-admin\`)
  Keycloak  https://auth.ec1.mateu.io     admin / \$KEYCLOAK_ADMIN_PASSWORD
  Grafana   https://grafana.ec1.mateu.io  admin / \$GRAFANA_ADMIN_PASSWORD
  Kafka     https://kafka.ec1.mateu.io    admin / \$KAFKA_CONSOLE_PASSWORD

Passwords are in $SECRETS.
Certificates take a minute: kubectl get certificate -A

To make a push to master reload the definitions, add two webhooks to the definitions
repository (Settings -> Webhooks), both with content type application/json, the "Just the
push event" trigger, and \$GIT_WEBHOOK_SECRET as the secret:

  https://ec1.mateu.io/workflow/webhooks/github
  https://ec1.mateu.io/forms/webhooks/github
EOF
